---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-pirata
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: front-pirata
  template:
    metadata:
      labels:
        app: front-pirata
    spec:
      containers:
      - name: front-pirata
        image: edez58/frontend-pirata-v1
        ports:
        - containerPort: 3000 
---
apiVersion: v1
kind: Service
metadata:
  name: front-svc
spec:
  selector:
    app: front-pirata 
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
